name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
    paths:
      - "package.json"
      - "src/**"
      - "tsconfig.json"

  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Run Rusalka
        uses: wxn0brP/rusalka@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
