name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"
    paths:
      - "package.json"
      - "src/**"
      - "tsconfig.json"

  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    uses: wxn0brP/workflow-dist/.github/workflows/build-ts.yml@main
    with:
      scriptsHandling: "remove-all"